### ISSUE TITLE
not work , blank page

### ISSUE THREAD

**Issue by L3GEND-IQ** [Abhilash-Ram/RestClient#2]
when i run <h4>index.html</h4> i just see blank page

**Comment by Abhilash-Ram** [comment]
Kindly be patience i am in creating new screen with updation from the previous issue sorry for the delay. it will be intimated after completion

**Comment by Abhilash-Ram** [comment]
Hi L3GEND-IQ,
I had check regarding your issue. it is not a issue. it is because we injected html into our app so cross orgin request error will occur when we run the index.html directly. it is good to use a web container to run that . for ex : you would have seen [link](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en-GB&utm_source=chrome-ntp-launcher) you could be able to add this addon on chrome extension for web container.

we had published this service in a website. it is a first release in production. so little development is done and uploaded.
